python src/main.py \
--method autoft \
--model ViT-B/16 \
--load PATH_TO_ZEROSHOT_MODEL \
--template fmow_template \
--data-location DATA_DIR \
--id FMOWTrain \
--id_val FMOWIDVal \
--ood FMOWOODVal \
--eval-datasets FMOWIDVal,FMOWIDTest,FMOWOODTest \
--ft_data DATA_DIR/csv/fmow_v1.1/fmow.csv --csv-img-key filepath --csv-caption-key title --get_labeled_csv \
--num_ood_hp_examples 1000 --use_class_balanced_ood \
--hopt_evals 500 --inner_steps 10 \
--losses ce dcm flyp entropy hinge l1init l1zero l2init l2zero --clip_gradient \
--ft_epochs 20 --lr 1e-5 --wd 0.1 --batch-size 256 --warmup_length 500
